steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/build-run-image-new', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/build-run-image-new']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'deployment.yaml', '--image', 'gcr.io/$PROJECT_ID/build-run-image-new', '--zone', 'us-central1-a', '--cluster',]
images:
- gcr.io/$PROJECT_ID/build-run-image-new
options:
  logging: CLOUD_LOGGING_ONLY
